[tool.poetry]
name = "service-health-guardian"
version = "0.1.0"
description = "A systemd service monitoring and management tool"
authors = ["Joel Mattsson joel.mattsson@hotmail.se"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.9.0"
pyyaml = "^6.0"
click = "^8.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
mypy = "^1.0.0"
black = "^22.0.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
service-guardian = "src.cli:main" 