# Services to monitor
services:
  - cron
  - snapd
  - sshd
  - nginx
  - docker
  - apache2
  - postgresql
  - mysql

  # Add more services as needed
  # - postgresql
  # - docker
  # - nginx
  # - apache2